services:
  stock-service:
    container_name: stock-service
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - 3334:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - try-network
    command: npm run start:dev

networks:
  try-network:
    driver: bridge
    name: try-network